# Use Node.js
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy rest of frontend
COPY frontend/ .

# Run React app
CMD ["npm", "start"]